# Generated by Django 3.2.12 on 2024-05-04 16:30
from django.db import migrations


def create_data(apps, schema_editor):
    menu_item = apps.get_model('spaceTourApp', 'MenuItem')
    advantage = apps.get_model('spaceTourApp', 'Advantage')
    menu_item(text="Главная", url="").save()
    menu_item(text="Технология", url="").save()
    menu_item(text="График полётов", url="").save()
    menu_item(text="Гарантии", url="").save()
    menu_item(text="О компании", url="").save()
    menu_item(text="Контакты", url="").save()
    advantage(heading="мы", content="1", description="на рынке").save()
    advantage(heading="гантируем", content="50%", description="безопасность").save()
    advantage(heading="календарик за", content="2001г.", description="в подарок").save()
    advantage(heading="путешествие", content="597", description="дней").save()


class Migration(migrations.Migration):

    dependencies = [
        ('spaceTourApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
