# Generated by Django 3.2.12 on 2024-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceTourApp', '0002_spaceTourApp'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='extra_content',
            field=models.CharField(blank=True, max_length=100, verbose_name='ExtraContent'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
    ]
